INSERT INTO comments (post_id, name, email, body)
VALUES
(1, 'John Doe', 'john.doe@example.com', 'Great post! I really enjoyed reading it.'),
(1, 'Michael Wilson', 'michael.wilson@example.com', 'The topic is relevant, and you explained it well.'),
(2, 'Alice Smith', 'alice.smith@email.com', 'Interesting insights. Thanks for sharing!'),
(2, 'Madison Brown', 'madison.brown@email.com', 'I had a similar thought, and your post articulated it perfectly.'),
(3, 'Bob Johnson', 'bob.johnson@example.com', 'I have a different perspective, but this is well-written.'),
(3, 'David Thomas', 'david.thomas@example.com', 'The real-world examples you provided are helpful.'),
(4, 'Emily Davis', 'emily.davis@email.com', 'This post resonates with my experiences.'),
(4, 'Ava Johnson', 'ava.johnson@email.com', "I've shared this with my colleagues. It sparked a good discussion."),
(5, 'Charlie Brown', 'charlie.brown@example.com', 'I learned something new today. Thanks!'),
(5, 'Jackson Lee', 'jackson.lee@example.com', "Your writing style is engaging. I couldn't stop reading."),
(6, 'Grace Wilson', 'grace.wilson@email.com', 'Looking forward to more content like this.'),
(6, 'Olivia Miller', 'olivia.miller@email.com', 'I appreciate the depth you went into on this topic.'),
(7, 'Daniel White', 'daniel.white@example.com', 'The examples provided are very helpful.'),
(7, 'Ethan Smith', 'ethan.smith@example.com', 'I found the information very valuable. Thank you!'),
(8, 'Olivia Miller', 'olivia.miller@email.com', 'I have a question about a point in the post. Can you clarify?'),
(8, 'Isabella White', 'isabella.white@email.com', "I'm looking forward to more posts from you."),
(9, 'Ethan Thomas', 'ethan.thomas@example.com', 'Well-researched and informative.'),
(9, 'Daniel Brown', 'daniel.brown@example.com', 'This post is a great resource for anyone looking to understand the topic better.'),
(10, 'Sophia Lee', 'sophia.lee@email.com', 'I appreciate the effort put into this post.'),
(10, 'Chloe Davis', 'chloe.davis@email.com', 'The length of the post is perfect. It kept me engaged throughout.'),
(11, 'Matthew Davis', 'matthew.davis@example.com', "This is a topic I've been curious about. Thanks for covering it!"),
(11, 'William Wilson', 'william.wilson@example.com', 'I had a question, and your post answered it. Thanks!'),
(12, 'Ava Johnson', 'ava.johnson@email.com', 'I disagree with a few points, but overall a good read.'),
(12, 'Sophia Miller', 'sophia.miller@email.com', 'I shared this on my social media. Others should read this too.'),
(13, 'James Wilson', 'james.wilson@example.com', 'I like the way you presented the information.'),
(13, 'Mason Lee', 'mason.lee@example.com', 'Your insights have given me a new perspective on the subject.'),
(14, 'Lily Brown', 'lily.brown@email.com', 'This post has inspired me to learn more about the subject.'),
(14, 'Ella Smith', 'ella.smith@email.com', 'I appreciate the effort you put into researching this.'),
(15, 'Christopher White', 'christopher.white@example.com', 'Kudos on a well-written post!'),
(15, 'Liam Davis', 'liam.davis@example.com', "I'm eager to see more content from you in the future."),
(16, 'Emma Smith', 'emma.smith@email.com', "I've bookmarked this for future reference."),
(16, 'Avery Johnson', 'avery.johnson@email.com', 'This post is a valuable addition to the discussion on this topic.'),
(17, 'Andrew Miller', 'andrew.miller@example.com', 'I had a similar experience, and your post captures it perfectly.'),
(17, 'Scarlett White', 'scarlett.white@example.com', 'Your post helped clarify some concepts I was confused about.'),
(18, 'Abigail Thomas', 'abigail.thomas@email.com', 'The length of the post is just right. Not too long, not too short.'),
(18, 'Benjamin Thomas', 'benjamin.thomas@example.com', "I've added this to my reading list. Well done!"),
(19, 'Henry Lee', 'henry.lee@example.com', 'I like the practical examples you included.'),
(19, 'Grace Brown', 'grace.brown@email.com', 'The examples you provided made it easy to understand.'),
(20, 'Sophie Davis', 'sophie.davis@email.com', 'This post made me think about things from a different perspective.'),
(20, 'Logan Wilson', 'logan.wilson@example.com', "I'm impressed by the depth of your analysis. Great job!");
